# Generated by Django 4.1.7 on 2023-03-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_aboutmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='name',
            field=models.TextField(default='', max_length=100),
        ),
    ]
