# Generated by Django 4.1.7 on 2023-03-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_aboutmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
