# Generated by Django 4.1.7 on 2023-02-20 11:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_tag_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='direction_list',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_list',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
