# Generated by Django 4.1.7 on 2023-03-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/cat-1.jpg', upload_to='categories/'),
        ),
    ]
