# Generated by Django 4.1.7 on 2023-03-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_number_of_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='number_of_likes',
        ),
    ]
